package model

import "errors"

var (
	ErrProductNotFound          = errors.New("Product Not Found")
	ErrCustomerNotFound         = errors.New("Customer Not Found")
	ErrOrderNotFound            = errors.New("Order Not Found")
	ErrInvalidQuantity          = errors.New("Invalid Quantity")
	ErrInsufficientStock        = errors.New("Insufficient Stock")
	ErrInvalidCustomer          = errors.New("Invalid Customer")
	ErrInvalidCustomerID        = errors.New("Invalid Customer ID")
	ErrEmptyOrder               = errors.New("Order must have at least one item")
	ErrInvalidStatusChange      = errors.New("Invalid Status Change")
	ErrEmailAlreadyExists       = errors.New("Email already exists")
	ErrNotNullViolation         = errors.New("Not null violation: a required field is missing")
	ErrInvalidJSON              = errors.New("Invalid JSON format")
	ErrInvalidUUID              = errors.New("ID must be a valid UUID")
	ErrInvalidQueryParam        = errors.New("Invalid query parameter format")
	ErrForeignKeyViolation      = errors.New("Foreign key violation: referenced entity not found")
	ErrCustomerNameRequired     = errors.New("Customer name is required")
	ErrCustomerNameTooShort     = errors.New("Customer name is too short")
	ErrCustomerNameTooLong      = errors.New("Customer name is too long")
	ErrCustomerEmailRequired    = errors.New("Customer email is required")
	ErrCustomerEmailInvalid     = errors.New("Customer email is invalid")
	ErrCustomerEmailTooLong     = errors.New("Customer email is too long")
	ErrCustomerPhoneRequired    = errors.New("Customer phone is required")
	ErrCustomerPhoneInvalid     = errors.New("Customer phone is invalid")
	ErrCustomerPhoneTooLong     = errors.New("Customer phone is too long")
	ErrCustomerPasswordRequired = errors.New("Customer password is required")
	ErrCustomerPasswordTooShort = errors.New("Customer password is too short")
	ErrCustomerPasswordTooLong  = errors.New("Customer password is too long")
	ErrProductNameRequired      = errors.New("Product name is required")
	ErrProductNameTooShort      = errors.New("Product name is too short")
	ErrProductNameTooLong       = errors.New("Product name is too long")
	ErrProductPriceRequired     = errors.New("Product price is required")
	ErrProductPriceTooLow       = errors.New("Product price cannot be zero or negative")
	ErrProductStockRequired     = errors.New("Product stock is required")
	ErrProductStockTooLow       = errors.New("Product stock cannot be zero or negative")
)
