package routes

import (
	_ "github.com/eneipereira/go-order-service/docs" // docs is generated by Swag CLI
	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger"
)

func RegisterSwaggerRoutes(router *chi.Mux) {
	router.Get("/swagger/*", httpSwagger.WrapHandler)
}
